# -*- coding: utf-8 -*-
"""Another copy of assingment 3 shahina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LaM23F5qDNewwIf2OAtzAPagr52Sxpu
"""

marks = {}
total = 0
subjects = ["Math", "English", "Physics", "Chemistry", "Urdu"]

for subject in subjects:
    marks[subject] = input("Enter " + subject + " marks : ")

for key in marks.values():
    total += int(key)

percentage = (total*100) / 500

if percentage >= 80:
    print("A")
elif percentage >= 60:
    print("B")
elif percentage >= 50:
    print("C")
else:
    print("Fail")

print(f"With a percentage of {percentage}%")

# Python program to check if year is a leap year or not

# year = 2000

# To get year (integer input) from the user
year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

celsius = float(input("Enterthe temperator in celsius : "))
fahrenheit = (celsius *1.8) + 32
print("%.2f c = %.2f F " %(celsius,fahrenheit))

fahrenheit = float(input("Enterthe temperator in fahrenheit : "))
celsius = (fahrenheit -32)/1.8
print("%.2f c = %.2f F " %(fahrenheit,celsius))